### ISSUE TITLE
Problems runing the sample code example with ver 1.2.0.2

### ISSUE THREAD

**Issue by Ramiloom** [STIXProject/java-stix#2]
Hi

I downloaded the jar release of stix-1.2.0.2 (I also compiled it by myself but I thought that maybe I did something wrong) and tried to run the sample code, XMLParser.java

I compile it using eclipce and get some errors

XMLParser:

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
    The type org.jvnet.jaxb2_commons.lang.ToString cannot be resolved. It is indirectly referenced from required .class files
    The type org.jvnet.jaxb2_commons.lang.HashCode cannot be resolved. It is indirectly referenced from required .class files
    The type org.jvnet.jaxb2_commons.lang.Equals cannot be resolved. It is indirectly referenced from required .class files

```
at org.mitre.stix.examples.XMLParser.main(XMLParser.java:53)
```

It looks like the org.jvnet.jaxb2_commons library that you depends on doesn't included inside your jar.

Hope you could help me

**Comment by KevinOnEarth** [comment]
Hi Ramiloom, 
It appears you will have to add jaxb_commons to your build path.  
See: 
http://confluence.highsource.org/display/J2B/JAXB2+Basics+Runtime

for a good (brief) description of its use and how to include it.

**Comment by nemonik** [comment]
Yep. And other runtime depends denoted as "compile" scope in the pom file. See the lengthy response sent to STIX discussion list.
