### ISSUE TITLE
Username and Password

### ISSUE THREAD

**Issue by leemeng-tecforte** [STIXProject/java-stix#3]
I tried to git clone https://github.com/STIXProject/java_stix.git but failed with Invalid username or password.

What's the username and password?

**Comment by leemeng-tecforte** [comment]
username and password is same as the login credentials in https://github.com

**Comment by nemonik** [comment]
You needed a user/password to clone?

**Comment by leemeng-tecforte** [comment]
There's typo in the README.MD, https://github.com/STIXProject/java_stix.git is wrong and it asked for username and password. Only the GitHub login will pass but it will give another error something like no such repository.

The correct git repo to clone is https://github.com/STIXProject/java-stix.git and it will not ask for username and password.

Sorry, tried too many ways and forgot to update you all.
