### ISSUE TITLE
Can't rename to Archive_File_Object.xsd : Permission denied

### ISSUE THREAD

**Issue by leemeng-tecforte** [STIXProject/java-stix#4]
I'm running the gradle in GIT Bash command window and get the error as mentioned above.

Below are the command window log:
$ ./gradlew -x signArchives
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:clean UP-TO-DATE
:retrieveSchemas
    Schemas are present. Retrieval is not needed.
    Patching C:\workspace\git\java-stix\src\main\resources\schemas\v1.2.0\cybox\
objects\Archive_File_Object.xsd
[ant:patch] patch: ***\* can't rename `/tmp/po010680' to`C:\workspace\git\java-stix\src\main\resources\schemas\v1.2.0\cybox\objects\Archive_File_Object.xsd' : Permission denied
[ant:patch] 'patch' failed with exit code 2
:createPrefixNamespaceBindings FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':createPrefixNamespaceBindings'.
  
  > 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

Total time: 7.465 secs

**Comment by nemonik** [comment]
I assume from 

```
Patching C:\workspace\git\java-stix\src\main\resources\schemas\v1.2.0\cybox\
objects\Archive_File_Object.xsd
```

you are on Windows.  Right?

As per [Building On Windows](https://github.com/STIXProject/java-stix#building-on-windows), for now what you are attempting is out of scope.  I'd advise you to build on Windows via the provided Dockerfile or retrieve and use the jars from the Maven Central Repository.  See [Releases](https://github.com/STIXProject/java-stix#releases).

Alternatively, you could patch Gradle to use ant to patch Archive_File_Object.xsd

like so [http://stackoverflow.com/questions/17064086/how-do-i-apply-a-patch-file-in-gradle](http://stackoverflow.com/questions/17064086/how-do-i-apply-a-patch-file-in-gradle).

Or make the changes by hand.

**Comment by leemeng-tecforte** [comment]
Yup thanks. I did by hand. Also can apply patch C:\workspace\git\java-stix\Archive_File_Object.xsd manually using any patch tools.

I've changed some code a bit here n there. I think almost done. Can push to your GIT repo when done?

**Comment by nemonik** [comment]
Propose a pull request and I will give it a look. Google "github making pull request".
